### ISSUE TITLE
Getting started tutorial

### ISSUE THREAD

**Issue by koegel** [eclipsesource/jsonforms#202]
<Story Description here>

Currently identified issues:
- [x] Control alignments with and without label #197 
- [x] Hide and show labels #183 
- [x] Github integration #173 
- [x] Visibility rules #172 
- [x] Multi line String Controls #166

**Comment by koegel** [comment]
This is a story since it will cover many issues.

**Comment by koegel** [comment]
Could you please describe the story textually in a paragraph

**Comment by edgarmueller** [comment]
From the issue point of view everything is set to complete the tutorial.
